[servers]

[servers.centos7]
host = "127.0.0.1"
port = "2221"
keyPath = "keys/id_ecdsa"
#scanMode           = ["fast", "fast-root", "deep", "offline"]
scanMode = ["fast"]
#type               = "pseudo"
#memo               = "DB Server"
#cpeNames           = [ "cpe:/a:rubyonrails:ruby_on_rails:4.2.1" ]
#owaspDCXMLPath     = "/path/to/dependency-check-report.xml"
#ignoreCves         = ["CVE-2014-0160"]
#containerType      = "docker" #or "lxd" or "lxc" default: docker
#containersIncluded = ["${running}"]
#containersExcluded = ["container_name_a"]

[servers.centos8]
host = "127.0.0.1"
port = "2222"
keyPath = "keys/id_ecdsa"
scanMode = ["fast"]

[servers.debian10]
host = "127.0.0.1"
port = "2223"
keyPath = "keys/id_ecdsa"
scanMode = ["fast"]

[servers.ubuntu18]
host = "127.0.0.1"
port = "2224"
keyPath = "keys/id_ecdsa"
scanMode = ["fast"]

# https://vuls.io/docs/en/usage-settings.html#default-section
[default]
#port = "22"
user = "vuls"

# https://vuls.io/docs/en/usage-settings.html
[cveDict]
type = "sqlite3"
SQLite3Path = "/path/to/db/cve.sqlite3"

[ovalDict]
type = "sqlite3"
SQLite3Path = "/path/to/db/oval.sqlite3"

[gost]
type = "sqlite3"
SQLite3Path = "/path/to/db/gost.sqlite3"

[exploit]
type = "sqlite3"
SQLite3Path = "/path/to/db/go-exploitdb.sqlite3"

[metasploit]
type        = "sqlite3"
SQLite3Path = "/path/to/db/go-msfdb.sqlite3"

# https://vuls.io/docs/en/usage-settings.html#slack-section
#[slack]
#hookURL = "https://hooks.slack.com/services/..."
##legacyToken = "xoxp-11111111111-222222222222-3333333333"
#channel      = "#channel-name"
##channel     = "${servername}"
#iconEmoji    = ":ghost:"
#authUser     = "username"
#notifyUsers  = ["@username"]