version: '3'

services:
  centos7:
    build: builds/centos7
    volumes:
      - ./data:/data
    ports:
      - '2221:22'
    command: '/bin/bash /data/init.sh'
    cap_add:
      - SYS_PTRACE  # for fast-root or deep scan

  centos8:
    build: builds/centos8
    volumes:
      - ./data:/data
    ports:
      - '2222:22'
    command: '/bin/bash /data/init.sh'
    cap_add:
      - SYS_PTRACE  # for fast-root or deep scan

  debian10:
    build: builds/debian10
    volumes:
      - ./data:/data
    ports:
      - '2223:22'
    command: '/bin/bash /data/init.sh'
    cap_add:
      - SYS_PTRACE  # for fast-root or deep scan

  ubuntu18:
    build: builds/ubuntu18
    volumes:
      - ./data:/data
    ports:
      - '2224:22'
    command: '/bin/bash /data/init.sh'
    cap_add:
      - SYS_PTRACE  # for fast-root or deep scan
  
  vlunhub:
    build: builds/vlunhub
    volumes:
      - ./data:/data
    ports:
      - '9999:22'
    command: '/bin/bash /data/init.sh'
    cap_add:
      - SYS_PTRACE  # for fast-root or deep scan
  
  vulsrepo:
      image: ishidaco/vulsrepo:latest
      command:
        - vulsrepo-server
      volumes:
        - ./results:/vuls/results
      ports:
        - "5111:5111"